import os
import shutil
from pathlib import Path
import pytest
from drivers.stirling_driver import StirlingDriver

WORKSPACE_ROOT = Path(__file__).resolve().parents[3]
ORIGINAL_EXE = WORKSPACE_ROOT / "analysis_target" / "Stirling.exe"
# Ported exe candidates for Win32 and x64
PORTED_EXE_WIN32_RELEASE = WORKSPACE_ROOT / "porting" / "StirHex" / "Release" / "bin" / "StirHex.exe"
PORTED_EXE_WIN32_DEBUG = WORKSPACE_ROOT / "porting" / "StirHex" / "Debug" / "bin" / "StirHex.exe"
PORTED_EXE_X64_RELEASE = WORKSPACE_ROOT / "porting" / "StirHex" / "x64" / "Release" / "bin" / "StirHex.exe"
PORTED_EXE_X64_DEBUG = WORKSPACE_ROOT / "porting" / "StirHex" / "x64" / "Debug" / "bin" / "StirHex.exe"


def get_ported_exe() -> Path:
    # 1. Environment variable for exact path (highest priority)
    env_exe = os.environ.get("STIRHEX_PORTED_EXE")
    if env_exe:
        exe_path = Path(env_exe)
        if not exe_path.exists():
            raise FileNotFoundError(
                f"StirHex.exe specified by STIRHEX_PORTED_EXE not found at {exe_path}"
            )
        exe = exe_path
    else:
        # 2. Candidate paths based on STIRLING_PLATFORM or default (x64 preferred)
        platform_env = os.environ.get("STIRLING_PLATFORM", "").strip()
        if platform_env.lower() in ("win32", "x86"):
            candidates = [PORTED_EXE_WIN32_RELEASE, PORTED_EXE_WIN32_DEBUG]
        elif platform_env.lower() in ("x64", "win64", "amd64"):
            candidates = [PORTED_EXE_X64_RELEASE, PORTED_EXE_X64_DEBUG]
        elif platform_env != "":
            raise ValueError(
                f"Unsupported STIRLING_PLATFORM='{platform_env}'. Expected 'Win32' or 'x64'."
            )
        else:
            # 既定は x64（移植版の既定プラットフォーム。Issue #23）。
            #   Win32 を試すときは STIRLING_PLATFORM=Win32 を指定する。
            candidates = [
                PORTED_EXE_X64_RELEASE,
                PORTED_EXE_X64_DEBUG,
                PORTED_EXE_WIN32_RELEASE,
                PORTED_EXE_WIN32_DEBUG,
            ]

        exe = None
        for cand in candidates:
            if cand.exists():
                exe = cand
                break

        if exe is None:
            cand_str = "\n".join(f"  - {p}" for p in candidates)
            raise FileNotFoundError(
                f"StirHex.exe not found. Searched candidates:\n{cand_str}"
            )

    # Ensure Struct.def exists in same directory as StirHex.exe
    target_def = exe.parent / "Struct.def"
    src_def = WORKSPACE_ROOT / "analysis_target" / "struct.def"
    if not target_def.exists() and src_def.exists():
        shutil.copy2(src_def, target_def)

    return exe


@pytest.fixture
def original_exe_path() -> Path:
    if not ORIGINAL_EXE.exists():
        pytest.skip(f"Original Stirling.exe not found at {ORIGINAL_EXE}")
    return ORIGINAL_EXE


@pytest.fixture
def ported_exe_path() -> Path:
    return get_ported_exe()


@pytest.fixture
def sample_binary_file(tmp_path) -> Path:
    """Generate a reproducible sample binary file (256 bytes sequence + ASCII)."""
    p = tmp_path / "sample.bin"
    # Create 256-byte sequence (0x00 .. 0xFF) followed by ASCII text
    data = bytes(range(256)) + b"Hello Stirling Binary Editor 2026! 0123456789\r\n"
    p.write_bytes(data)
    return p


@pytest.fixture
def run_both_stirling(original_exe_path, ported_exe_path, tmp_path):
    """Fixture that helper executes an identical operation sequence on both original and ported Stirling,
    and returns paths to the outputs generated by both."""
    
    def _runner(action_fn, initial_data: bytes) -> tuple[bytes, bytes]:
        # Prepare inputs with .dat extension (uses default Rec0 display setting: LineSize=16, AddressBase=16hex)
        orig_in = tmp_path / "in_orig.dat"
        port_in = tmp_path / "in_port.dat"
        orig_out = tmp_path / "out_orig.dat"
        port_out = tmp_path / "out_port.dat"

        orig_in.write_bytes(initial_data)
        port_in.write_bytes(initial_data)

        # Run on original
        with StirlingDriver(original_exe_path) as drv_orig:
            drv_orig.start(orig_in)
            action_fn(drv_orig, orig_out)
        
        # Run on ported
        with StirlingDriver(ported_exe_path) as drv_port:
            drv_port.start(port_in)
            action_fn(drv_port, port_out)

        orig_result = orig_out.read_bytes() if orig_out.exists() else b""
        port_result = port_out.read_bytes() if port_out.exists() else b""
        return orig_result, port_result

    return _runner
